menus:
	- 
		name: 首页
		link: /
	- 
		name: 分类
		link: category/
	- 
		name: 开源项目
		link: open-source/
	- 
		name: 留言板
		link: message/

profile:
	location: Beijing, China
	github: ihewro
	#stackoverflow: 
		#title: yumemor
		#href: http://stackoverflow.com/users/5662132/yumemor
	#organization: 组织/公司

github: 
	username: yumemor
  popular_repos: [typecho-theme-handsome,typecho-theme-leaf,typecho-theme-greenray,Duoshuo-Disqus-theme,typecho-theme-book]

comment:
	#duoshuo_username: 
	disqus_username: wiki-ihewro 

search: local #google｜local
